services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    healthcheck:
      test: "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"
      interval: 10s

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy

  brand-ms:
    build: ./brand-microservice
    container_name: brand-ms
    ports:
      - "8082:8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  brand-ms2:
    build: ./brand-microservice
    container_name: brand-ms2
    ports:
      - "8084:8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  moto-ms:
    build: ./moto-microservice
    container_name: moto-ms
    ports:
      - "8081:8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      brand-ms:
        condition: service_healthy